before_script:
    - mkdir ~/.ssh
    - echo $SSH_PRIVATE_KEY > ~/.ssh/id_rsa

stages:
    - deploy

mirror:
    stage: deploy
    script:
        - git status
        - git push "git@github.com:chancefocus/python-base-image.git" $CI_COMMIT_REF_NAME
    only:
        - branches
        - tags
