before_script:
    - mkdir ~/.ssh
    - echo $SSH_PRIVATE_KEY > ~/.ssh/id_rsa
    - echo $SSH_PUBLIC_KEY > ~/.ssh/id_rsa.pub
    - ssh-keyscan -H -t rsa github.com >> ~/.ssh/known_hosts
    - mknod -m 666 /dev/tty c 5 0
    - chmod 400 ~/.ssh/id_rsa

stages:
    - deploy

mirror:
    stage: deploy
    script:
        - ssh -vT git@github.com
        - git checkout $CI_COMMIT_REF_NAME
        - git push "git@github.com:chancefocus/python-base-image.git" $CI_COMMIT_REF_NAME
    only:
        - branches
        - tags
