before_script:
    - mkdir ~/.ssh
    - echo $SSH_PRIVATE_KEY > ~/.ssh/id_rsa
    - ssh-keyscan -H -t rsa github.com >> ~/.ssh/known_hosts

stages:
    - deploy

mirror:
    stage: deploy
    script:
        - git checkout $CI_COMMIT_REF_NAME
        - git push "git@github.com:chancefocus/python-base-image.git" $CI_COMMIT_REF_NAME
    only:
        - branches
        - tags
